# Actividad 1: Carga y Creación de Dataset

### Grupo: AE_Grupo_6
Integrantes:
* Juan Fernando Gaviria Higuita
* Juan David Ramírez García

# Semana 1: Carga y reporte de el dataset HealthRiskPredictor

Enlace en huggingface del dataset:[HealthRiskPredictor](https://huggingface.co/datasets/infinite-dataset-hub/HealthRiskPredictor)

### 1. Importar las dos clases desde sus archivos .py

Preparar el entorno e importar la clase de carga

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT / "src"))

from clases_po import HFDatasetLoader

/home/runner/work/ML_2026Q4/ML_2026Q4/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 2. Usar la primera clase para obtener el DataFrame desde Hugging Face.

Configurar el dataset y la salida

In [2]:
loader = HFDatasetLoader(
    dataset_name="infinite-dataset-hub/HealthRiskPredictor",
    split="train",
    filename="datos/health_risk_predictor.csv",
)

descargando y creando  el DataFrame

In [3]:
df = loader.load()
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating train split:   0%|          | 0/91 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 91/91 [00:00<00:00, 17886.58 examples/s]

,idx,age,gender,weight,height,exercise_frequency,smoking_status,diet_type,family_history_of_diseases,medical_history,risk_level
0,0,29,male,85,180,4,non-smoker,balanced,no,none,low
1,1,35,female,70,165,2,smoker,vegan,yes,hypertension,high
2,2,42,male,95,175,1,non-smoker,omnivore,no,none,medium
3,3,58,female,78,160,3,non-smoker,vegetarian,yes,diabetes,high
4,4,33,male,88,178,2,non-smoker,balanced,no,none,low

Revisando la estructura del DataFrame

In [4]:
print(f"Filas: {len(df)}")
print(f"Columnas: {len(df.columns)}")
df.info()

Filas: 91
Columnas: 11
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   idx                         91 non-null     int64
 1   age                         91 non-null     int64
 2   gender                      91 non-null     object
 3   weight                      91 non-null     int64
 4   height                      91 non-null     int64
 5   exercise_frequency          91 non-null     int64
 6   smoking_status              91 non-null     object
 7   diet_type                   91 non-null     object
 8   family_history_of_diseases  91 non-null     object
 9   medical_history             91 non-null     object
 10  risk_level                  91 non-null     object
dtypes: int64(5), object(6)
memory usage: 7.9+ KB

### 3. Aplicar una transformación mínima al DataFrame cargado.

In [5]:
# 1. Eliminar la columna redundante 'idx' porque es la misma que el índice del DataFrame
df = df.drop(columns=["idx"])
# Verificación de la lista de columnas
print(f"Verificando que la columna 'idx' ha sido eliminada:\n{df.columns}")

Verificando que la columna 'idx' ha sido eliminada:
Index(['age', 'gender', 'weight', 'height', 'exercise_frequency',
       'smoking_status', 'diet_type', 'family_history_of_diseases',
       'medical_history', 'risk_level'],
      dtype='object')

In [6]:
# Calculando el Índice de Masa Corporal (IMC)
df.loc[:, "bmi"] = df["weight"] / ((df["height"] / 100) ** 2)
print("Se ha calculado el Índice de Masa Corporal (IMC) y se ha agregado como una nueva columna 'bmi'.")
df.head(2)

Se ha calculado el Índice de Masa Corporal (IMC) y se ha agregado como una nueva columna 'bmi'.

,age,gender,weight,height,exercise_frequency,smoking_status,diet_type,family_history_of_diseases,medical_history,risk_level,bmi
0,29,male,85,180,4,non-smoker,balanced,no,none,low,26.234568
1,35,female,70,165,2,smoker,vegan,yes,hypertension,high,25.711662

In [7]:
# Convirtiendo a variable ordinal de la variable objetivo ('risk_level')
risk_mapping = {"low": 0, "medium": 1, "high": 2}
df.loc[:, "risk_level_encoded"] = df["risk_level"].map(risk_mapping)

print("Se ha convertido la variable objetivo 'risk_level' a una variable ordinal 'risk_level_encoded'.")
df.head(2)

Se ha convertido la variable objetivo 'risk_level' a una variable ordinal 'risk_level_encoded'.

,age,gender,weight,height,exercise_frequency,smoking_status,diet_type,family_history_of_diseases,medical_history,risk_level,bmi,risk_level_encoded
0,29,male,85,180,4,non-smoker,balanced,no,none,low,26.234568,0
1,35,female,70,165,2,smoker,vegan,yes,hypertension,high,25.711662,2

### 4. Pasar el DataFrame transformado a la segunda clase para generar el resumen en .txt.

Importando la clase de reportes

In [8]:
from clases_po import Reportes

Generando y visualizando el reporte como texto

In [9]:
reportes = Reportes()
texto = reportes.generar_reporte(df)

print(texto)

REPORTE DEL DATAFRAME
============================================================
Filas: 91
Columnas: 12
Duplicados: 6

Columnas y tipos:
- age: int64
- gender: object
- weight: int64
- height: int64
- exercise_frequency: int64
- smoking_status: object
- diet_type: object
- family_history_of_diseases: object
- medical_history: object
- risk_level: object
- bmi: float64
- risk_level_encoded: int64

Valores nulos por columna:
- age: 0
- gender: 0
- weight: 0
- height: 0
- exercise_frequency: 0
- smoking_status: 0
- diet_type: 0
- family_history_of_diseases: 0
- medical_history: 0
- risk_level: 0
- bmi: 0
- risk_level_encoded: 0

Estadísticas numéricas:
          age   weight   height  exercise_frequency     bmi  risk_level_encoded
count  91.000   91.000   91.000              91.000  91.000              91.000
mean   41.253   78.088  170.341               2.505  26.828               1.022
std    10.557   10.855    7.850               1.649   2.559               0.816
min    22.000   56.000  155.000               0.000  20.761               0.000
25%    31.500   69.500  165.000               1.000  25.450               0.000
50%    44.000   77.000  170.000               2.000  26.892               1.000
75%    50.000   88.000  175.500               4.000  28.407               2.000
max    65.000  102.000  185.000               6.000  31.834               2.000

 Imprimiendo el reporte directamente

In [10]:
reportes.imprimir_reporte(df)

REPORTE DEL DATAFRAME
============================================================
Filas: 91
Columnas: 12
Duplicados: 6

Columnas y tipos:
- age: int64
- gender: object
- weight: int64
- height: int64
- exercise_frequency: int64
- smoking_status: object
- diet_type: object
- family_history_of_diseases: object
- medical_history: object
- risk_level: object
- bmi: float64
- risk_level_encoded: int64

Valores nulos por columna:
- age: 0
- gender: 0
- weight: 0
- height: 0
- exercise_frequency: 0
- smoking_status: 0
- diet_type: 0
- family_history_of_diseases: 0
- medical_history: 0
- risk_level: 0
- bmi: 0
- risk_level_encoded: 0

Estadísticas numéricas:
          age   weight   height  exercise_frequency     bmi  risk_level_encoded
count  91.000   91.000   91.000              91.000  91.000              91.000
mean   41.253   78.088  170.341               2.505  26.828               1.022
std    10.557   10.855    7.850               1.649   2.559               0.816
min    22.000   56.000  155.000               0.000  20.761               0.000
25%    31.500   69.500  165.000               1.000  25.450               0.000
50%    44.000   77.000  170.000               2.000  26.892               1.000
75%    50.000   88.000  175.500               4.000  28.407               2.000
max    65.000  102.000  185.000               6.000  31.834               2.000

Guardando el reporte en un archivo de texto

In [11]:
ruta = reportes.guardar_reporte(
    df,
    "reportes/health_risk_predictor.txt",
)

print(f"Reporte guardado en: {ruta}")

Reporte guardado en: reportes/health_risk_predictor.txt

### 5. Mostrar el resultado y explicar brevemente qué transformación se hizo.

In [12]:
# Mostrando DataFrame final con las nuevas columnas
df.head(2)

,age,gender,weight,height,exercise_frequency,smoking_status,diet_type,family_history_of_diseases,medical_history,risk_level,bmi,risk_level_encoded
0,29,male,85,180,4,non-smoker,balanced,no,none,low,26.234568,0
1,35,female,70,165,2,smoker,vegan,yes,hypertension,high,25.711662,2

###  Resultado y explicación de las transformaciones



1. **Eliminación de `idx`:** Se removió la columna identificadora por ser redundante con el índice interno de Pandas ($i \in \{0, 1, \dots, n-1\}$).

2. **Creación de `bmi` ($\text{IMC}$):** Se combinaron el peso ($\text{weight}$) y la estatura ($\text{height}$) en una nueva variable  usando la fórmula del Índice de Masa Corporal:

   $$\text{BMI} = \frac{\text{weight}_{\text{kg}}}{\left(\frac{\text{height}_{\text{cm}}}{100}\right)^2}$$

3. **Codificación ordinal de `risk_level_encoded`:** Se transformaron las categrorías de texto a valores numéricos como 0, 1, 2,..  para permitir su evaluación matemática en modelos predictivos: